apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/my-cluster-gitops.git
    targetRevision: main
    path: clusters/mycluster/apps   # child Application yamls live here
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # First time: keep manual. After you verify, turn on automated.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
