apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-accept-backend
  namespace: expense
spec:
  podSelector:
    matchLabels:
       app: mysql
       project: expense
       tier: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend
          tier: backend
          project: expense
    ports:
    - protocol: TCP
      port: 3306
